---
device_os: eos
provider: "{{ cli }}"

cli:
  host: "{{ eos_cli_host | default(inventory_hostname) }}"
  username: "{{ eos_cli_user | default('admin') }}"
  password: "{{ eos_cli_pass | default('admin') }}"
  authorize: yes
  transport: cli

eapi:
  host: "{{ eos_cli_host | default(inventory_hostname) }}"
  username: "{{ eos_eapi_user | default('admin') }}"
  password: "{{ eos_eapi_pass | default('admin') }}"
  authorize: yes
  use_ssl: no
  transport: eapi


# NTP settings
ntp_source_interface: Management1

