---
device_os: iosxr
provider: "{{ cli }}"

cli:
  host: "{{ ios_cli_host | default(inventory_hostname) }}"
  username: "{{ ios_cli_user | default('root') }}"
  password: "{{ ios_cli_pass | default('root') }}"
  transport: cli

