---
- name: checkout latest config templates
  git:
    repo: https://github.com/privateip/config-templates.git
    dest: "{{ playbook_dir }}/templates"

- name: include device specific tasks
  include: "{{ item }}"
  with_first_found:
    - files: "{{ device_os }}.yaml"
      skip: true
      paths: "tasks/{{ state }}"

