---
- name: manage NTP parameters on network devices
  hosts: "{{ devices | default('all') }}"
  gather_facts: no
  connection: local

  roles:
    - role: ntp
      state: present
      ntp_servers:
        - 0.us.pool.ntp.org
        - 1.us.pool.ntp.org
        - 2.us.pool.ntp.org
        - 3.us.pool.ntp.org


