---
- name: configure network device system services
  hosts: "{{ devices | default('all') }}"
  gather_facts: no
  connection: local

  pre_tasks:
    - name: checkout latest config templates
      git:
        repo: https://github.com/privateip/config-templates.git
        dest: "{{ playbook_dir }}/templates"

  roles:
    - role: system_vcs
      state: present
      system_hostname: "{{ inventory_hostname }}"
      system_domain_name: eng.ansible.com
      system_source_interface: "{{ system.source_interface }}"
      system_name_servers:
        - 172.26.1.1

