---
- name: set links fact
  set_fact: links="{{ links[interface_name] }}"
  when: interface_name is defined

- name: "include {{ device_os }} tasks"
  include: "{{ item }}"
  with_first_found:
    - files: "{{ device_os }}.yaml"
      skip: true
      paths: "tasks/{{ state }}"
  when: links is defined

